Add Experimental Initial Span
mono/CppSharp pull request #1651
Opened 2022-02-16 16:46 UTC by AhmedZero

2022-02-19 03:45 UTC, tritao requested changes

2022-02-19 03:45 UTC, tritao commented on src/Generator/Generators/CSharp/CSharpTypePrinter.cs
> +            if (!(array.SizeType != ArrayType.ArraySize.Constant &&  MarshalKind == MarshalKind.ReturnVariableArray) && Context.Options.UseSpan)
This is missing a new line here before the if.

2022-02-19 03:45 UTC, tritao commented on src/Generator/Generators/CSharp/CSharpTypePrinter.cs
Remove the extra line here.

2022-02-19 03:45 UTC, tritao commented on src/Generator/Options.cs
> +        public bool UseSpan { get; set; }
Please document this option with XML comments and remove the extra new lines.

2022-02-19 03:45 UTC, tritao commented on src/Generator/Generators/CSharp/CSharpMarshal.cs
> +                        if (Context.Context.Options.UseSpan)
Please add brackets to the if here. The way its nested can lead to bugs.

2022-02-19 03:45 UTC, tritao commented on src/Generator/Generators/CSharp/CSharpMarshal.cs
>                      else if (array.Type.IsPointerToPrimitiveType(PrimitiveType.Void))
Please add brackets to the if here. The way its nested can lead to bugs.

2022-02-19 10:23 UTC, AhmedZero commented
Review again thanks.

2022-02-23 16:15 UTC, merged

2022-02-23 16:16 UTC, tritao commented
Thanks!